### ISSUE TITLE
Release file

### ISSUE THREAD

**Issue by nilskp** [gaberankin/koala-jade#2]
Why not build this and provide it as a release, so we don't all have to build it?

**Comment by gaberankin** [comment]
Because honestly I've been a whiney baby and didn't want to admit that not everyone wants to do that kind of thing.  Additionally, I haven't been paying much attention to the repo.  I created the project on a whim one day and didn't really use it much since then.

I've pulled my head out of my butt though, and I apologize for ignoring your issue.

**Comment by nilskp** [comment]
@gaberankin Great, thanks.
