### ISSUE TITLE
node_modules

### ISSUE THREAD

**Issue by rabet** [gaberankin/koala-jade#4]
Hey,

which exactly "node_modules" should I add to the zip file?

Thanks a lot!
T.

**Comment by gaberankin** [comment]
Ah!  hmm yes.  Reading the README, it looks like I left out a few steps.  I had assumed that the user would run `npm install` within the directory after cloning.  This is something I took for granted and I apologize.  I'm going to get that corrected.

Additionally, perhaps I should actually do something about issue #2 so that users don't have to actually go through the process of building and reading my bad instructions.

**Comment by gaberankin** [comment]
Oh.  looks like I *did* include the "run `npm install`" step.  Sorry.  it's still early here.

Yeah, so, npm (or "Node Package Manager") is a tool installed along side node that helps developers install packages to their projects through the command line.  it is analogous to things like composer (for PHP), pip (for python), and probably most notably gem (for ruby).  When a node project has a `package.json` file in its base directory, it will often define dependencies that the project needs.  When you run `npm install` (after installing node of course) in the project directory, npm reads the `package.json` file, determines the dependencies, downloads them, and creates a `node_modules` directory.

Regardless, I agree with @nilskp that I should be including the zip in the project (see issue #2).

**Comment by gaberankin** [comment]
If you do another pull now, you can get the plugin without having to build it yourself.

**Comment by rabet** [comment]
Hey Gabe,

thanks a lot for your broad answer. I figured the right method a couple of days ago. I'm quite new with the nodejs and all this stuff so my apologies for the misunderstanding of the (now yet clear and simple) build process :)

r
